apiVersion: v1
kind: Service
metadata:
  name: vibrox-core
spec:
  selector:
    app: vibrox-core
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8080
  # vibrox-web is the public entry point and proxies /api requests here.
  type: ClusterIP
