apiVersion: apps/v1
kind: Deployment
metadata:
  name: vibrox-core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vibrox-core
  template:
    metadata:
      labels:
        app: vibrox-core
    spec:
      containers:
        - name: vibrox-core
          image: viburoshin25/vibrox-core:latest
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            periodSeconds: 10
            initialDelaySeconds: 10
          env:
            - name: LOGGER_HOST
              value: vibrox-echo:9000
            - name: ARENA_HOST
              value: vibrox-arena:8100
